// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Ib9cDMJa6ukO0XlHBbWuEBipRzCSicQ',
    appId: '1:308079529145:web:c8038046a27f45c3a2df68',
    messagingSenderId: '308079529145',
    projectId: 'secciona-1aaea',
    authDomain: 'secciona-1aaea.firebaseapp.com',
    storageBucket: 'secciona-1aaea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU3RYRoPXnTjcSfK1mjGzdJtkhPvosy3k',
    appId: '1:308079529145:android:4368c0a984cd4537a2df68',
    messagingSenderId: '308079529145',
    projectId: 'secciona-1aaea',
    storageBucket: 'secciona-1aaea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Kh3WeHV3VF4Rs6LITTJjONtIqF0LiiM',
    appId: '1:308079529145:ios:8979eca271dc4edda2df68',
    messagingSenderId: '308079529145',
    projectId: 'secciona-1aaea',
    storageBucket: 'secciona-1aaea.appspot.com',
    iosClientId: '308079529145-cbt5r0pnpikghbs0rld8tggoq66c3lab.apps.googleusercontent.com',
    iosBundleId: 'com.example.neflis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Kh3WeHV3VF4Rs6LITTJjONtIqF0LiiM',
    appId: '1:308079529145:ios:6d90d8c7e1065ef6a2df68',
    messagingSenderId: '308079529145',
    projectId: 'secciona-1aaea',
    storageBucket: 'secciona-1aaea.appspot.com',
    iosClientId: '308079529145-904q0o2b53coffco38tg75arj6q2j1nv.apps.googleusercontent.com',
    iosBundleId: 'com.example.neflis.RunnerTests',
  );
}
